"""empty message

Revision ID: 6350e4840e5b
Revises: 
Create Date: 2022-03-08 13:51:50.622913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6350e4840e5b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('climate_select',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=72), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('color_select',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('color_name', sa.String(length=72), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('color_name'),
    sa.UniqueConstraint('color_name')
    )
    op.create_table('gender_select',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=72), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ship_class_select',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=72), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ship_maker_select',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=72), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('terrain_select',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=72), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('user_password', sa.String(length=32), nullable=False),
    sa.Column('user_avatar', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('username')
    )
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=72), nullable=False),
    sa.Column('gender_id', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(length=250), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('mass', sa.Integer(), nullable=True),
    sa.Column('hair_color', sa.Integer(), nullable=True),
    sa.Column('skin_color', sa.Integer(), nullable=True),
    sa.Column('eye_color', sa.Integer(), nullable=True),
    sa.Column('birht_year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['eye_color'], ['color_select.id'], ),
    sa.ForeignKeyConstraint(['gender_id'], ['gender_select.id'], ),
    sa.ForeignKeyConstraint(['hair_color'], ['color_select.id'], ),
    sa.ForeignKeyConstraint(['skin_color'], ['color_select.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=72), nullable=False),
    sa.Column('image', sa.String(length=250), nullable=True),
    sa.Column('rotation_period', sa.Integer(), nullable=True),
    sa.Column('orbital_period', sa.Integer(), nullable=True),
    sa.Column('gravity', sa.Integer(), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('climate_id', sa.Integer(), nullable=True),
    sa.Column('terrain_id', sa.Integer(), nullable=True),
    sa.Column('surface_water', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['climate_id'], ['climate_select.id'], ),
    sa.ForeignKeyConstraint(['terrain_id'], ['terrain_select.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('starships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=72), nullable=False),
    sa.Column('image', sa.String(length=250), nullable=True),
    sa.Column('starship_class', sa.Integer(), nullable=True),
    sa.Column('manufacturer', sa.Integer(), nullable=True),
    sa.Column('cost_in_credits', sa.Integer(), nullable=True),
    sa.Column('lenght', sa.Integer(), nullable=True),
    sa.Column('crew', sa.Integer(), nullable=True),
    sa.Column('passengers', sa.Integer(), nullable=True),
    sa.Column('max_atmopheric_speed', sa.Integer(), nullable=True),
    sa.Column('hyperdrive_rating', sa.Integer(), nullable=True),
    sa.Column('mglt', sa.Integer(), nullable=True),
    sa.Column('cargo_capacity', sa.Integer(), nullable=True),
    sa.Column('consumable', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['manufacturer'], ['ship_maker_select.id'], ),
    sa.ForeignKeyConstraint(['starship_class'], ['ship_class_select.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ship_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('planet_id', sa.Integer(), nullable=True),
    sa.Column('char_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['char_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['planet_id'], ['planets.id'], ),
    sa.ForeignKeyConstraint(['ship_id'], ['starships.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('homeworld',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=False),
    sa.Column('char_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['char_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['planet_id'], ['planets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pilots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('starships_id', sa.Integer(), nullable=False),
    sa.Column('char_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['char_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['starships_id'], ['starships.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pilots')
    op.drop_table('homeworld')
    op.drop_table('favorite')
    op.drop_table('starships')
    op.drop_table('planets')
    op.drop_table('characters')
    op.drop_table('user')
    op.drop_table('terrain_select')
    op.drop_table('ship_maker_select')
    op.drop_table('ship_class_select')
    op.drop_table('gender_select')
    op.drop_table('color_select')
    op.drop_table('climate_select')
    # ### end Alembic commands ###
