"""empty message

Revision ID: ae8c871cce33
Revises: e59a047dd10d
Create Date: 2022-03-10 13:04:05.902109

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ae8c871cce33'
down_revision = 'e59a047dd10d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('planets', 'climate_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('planets', 'terrain_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('planets', 'terrain_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('planets', 'climate_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
