"""empty message

Revision ID: c04cfd107fd6
Revises: ae8c871cce33
Create Date: 2022-03-10 14:54:49.522703

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c04cfd107fd6'
down_revision = 'ae8c871cce33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('birth_year', sa.Integer(), nullable=True))
    op.drop_column('characters', 'birht_year')
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_active')
    op.add_column('characters', sa.Column('birht_year', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('characters', 'birth_year')
    # ### end Alembic commands ###
