"""empty message

Revision ID: e59a047dd10d
Revises: 59da39129d49
Create Date: 2022-03-10 11:42:28.183494

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e59a047dd10d'
down_revision = '59da39129d49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('planets', 'climate_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('planets', 'terrain_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('planets', 'terrain_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('planets', 'climate_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
